meta-aspeed/recipes-kernel/linux/linux-aspeed_git.bb

Ben Pai (1):
ARM: dts: aspeed: Add Mihawk BMC platform
Change-Id: I1ece8d9b817cfc1d20663cf9692135e76bcf3bba
Signed-off-by: Joel Stanley <joel@jms.id.au>

linux-aspeed: Add Mihawk

---

meta-ibm/meta-witherspoon/conf/machine/witherspoon.conf

Upstream change - https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/24428

witherspoon: Bump MRW version

---

meta-ibm/meta-witherspoon/conf/machine/mihawk.conf
meta-ibm/meta-witherspoon/recipes-phosphor/images/obmc-phosphor-image.bbappend
meta-ibm/meta-witherspoon/recipes-phosphor/network/first-boot-set-mac_%.bbappend
meta-ibm/meta-witherspoon/recipes-phosphor/vpd/mihawk-openpower-fru-inventory-native.bb
meta-ibm/meta-witherspoon/recipes-phosphor/vpd/mihawk-openpower-fru-inventory/inventory
meta-ibm/meta-witherspoon/recipes-phosphor/vpd/mihawk-openpower-fru-vpd-layout-native.bb
meta-ibm/meta-witherspoon/recipes-phosphor/vpd/mihawk-openpower-fru-vpd-layout/layout.yaml

(From meta-ibm rev: effd83bdc65d9ae8f9d000205f8d55e0c29557e4)
Change-Id: I5d8fb1cd15e0b0bf2c2360631be8f259f42be98f
Signed-off-by: Alvin Wang <alvinwang@msn.com>

Add Mihawk mac address sync

---

meta-openpower/recipes-phosphor/network/first-boot-set-mac/first-boot-set-mac.sh

(From meta-openpower rev: 94da1d8dee685dbfb062f457597265289d369295)
Change-Id: I0df0ad8b66d8dfc7774bf3af73a08eed26a6d497
Signed-off-by: Alvin Wang <alvinwang@msn.com>

Add two MAC addresses support for Mihawk's 2 NICs

---

meta-ibm/meta-witherspoon/recipes-phosphor/gpu/phosphor-gpu/xyz.openbmc_project.gpu.manager.service
meta-ibm/meta-witherspoon/recipes-phosphor/gpu/phosphor-gpu_git.bb
meta-ibm/meta-witherspoon/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend

Mihawk fan control support gpu thermal sensor. 
_Please_ do not submit a Pull Request via github.  Our project makes use of

Add GPU temperature sensor reading for mihawk.

---

meta-ibm/meta-witherspoon/recipes-phosphor/network/network/ncsi-netlink.service

Upstream commits:
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/25825/1
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/25835/2
See defect or commit text for more info

SW477765: Op940 ncsi service fix

---

meta-ibm/meta-witherspoon/recipes-phosphor/logging/ibm-logging/ibm-ac-server/policyTable.json

Version 1.8.4
SW479717
Gerrit commit at https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/26713
Signed-off-by: Matt Spinler <spinler@us.ibm.com>

wspoon: New IBM logging error policy table

---

meta-aspeed/recipes-kernel/linux/linux-aspeed.inc
meta-aspeed/recipes-kernel/linux/linux-aspeed/0001-hwmon-pmbus-ibm-cffps-Fix-LED-blink-behavior.patch
meta-aspeed/recipes-kernel/linux/linux-aspeed/0002-hwmon-pmbus-ibm-cffps-Don-t-relinquish-control-of-LE.patch
meta-aspeed/recipes-kernel/linux/linux-aspeed_git.bb

Signed-off-by: Eddie James <eajames@linux.ibm.com>

kernel: Revert to 5.3.1 and add PSU driver fix

---

meta-openpower/recipes-phosphor/flash/openpower-software-manager_git.bb

Adriana Kobylak (1):
op-pnor-msl.service: Remove RemainAfterExit
Change-Id: I0b3bdb8245359fed323886bdedaf423476a9f2d1

openpower-pnor-code-mgmt branch=OP940 SRCREV bump daee925e..f666dd0b

---

meta-ibm/meta-witherspoon/conf/machine/mowgli.conf

meta-ibm: Update mowgli mrw version

---

meta-ibm/meta-witherspoon/recipes-phosphor/sensors/phosphor-hwmon/mowgli/obmc/hwmon/ahb/apb/bus@1e78a000/i2c-bus@100/power-supply@68.conf
meta-ibm/meta-witherspoon/recipes-phosphor/sensors/phosphor-hwmon/mowgli/obmc/hwmon/ahb/apb/bus@1e78a000/i2c-bus@100/power-supply@69.conf
meta-ibm/meta-witherspoon/recipes-phosphor/sensors/phosphor-hwmon_%.bbappend

Added psu voltage, current and power sensor.

meta-ibm: Add mowgli psu sensor

---

meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis.inc

Update the version of witherspoon-pfault-analysis for fixing the
clearRegister function issue of mowgli.

Fix the issue of clearRegister function for mowgli

---

meta-ibm/meta-witherspoon/conf/machine/mowgli-oem.conf
meta-ibm/meta-witherspoon/conf/machine/mowgli.conf
meta-ibm/meta-witherspoon/recipes-phosphor/webui/phosphor-webui/0001-Change-IBM-logo-to-OpenBmc-logo.patch
meta-ibm/meta-witherspoon/recipes-phosphor/webui/phosphor-webui_%.bbappend

Replace the IBM logo with the original OpenBMC logo, so add a new
machine.

meta-ibm: Add mowgli-oem machine

---

meta-ibm/meta-witherspoon/recipes-phosphor/logging/ibm-logging/mowgli/policyTable.json

Because of the requirements of the IBM HMC team, update the
policyTable of mowgli.

Update the policyTable of mowgli

---

meta-ibm/meta-witherspoon/recipes-phosphor/settings/phosphor-settings-manager_%.bbappend

meta-ibm: Support for Key Clear functionality

---

meta-ibm/meta-witherspoon/conf/machine/mowgli-oem.conf

meta-ibm: Fix this typo

---

meta-ibm/meta-witherspoon/recipes-phosphor/webui/phosphor-webui/blankLogo.svg
meta-ibm/meta-witherspoon/recipes-phosphor/webui/phosphor-webui/change-logo.service
meta-ibm/meta-witherspoon/recipes-phosphor/webui/phosphor-webui/changeLogo.sh
meta-ibm/meta-witherspoon/recipes-phosphor/webui/phosphor-webui_%.bbappend

Add change-logo service to detect whether there is a keyword in the
VPD, if it exists, the original logo will be replaced with a blank logo.
Signed-off-by: Ben Pai Ben_Pai@wistron.com
Signed-off-by: LuluTHSu Lulu_Su@wistron.com

meta-ibm: Add the change-logo service for mowgli

---

meta-phosphor/recipes-phosphor/configuration/entity-manager_git.bb

Change-Id: Ibce6144ae12d58589f894edb609ab2622517b5d2

ibm-openbmc: entity-manager: downstream srcrev bump 9d983212b7..173dac43c7

---

poky/meta/recipes-connectivity/openssl/openssl/0001-buildinfo-strip-sysroot-and-debug-prefix-map-from-co.patch
poky/meta/recipes-connectivity/openssl/openssl/0003-Add-support-for-io_pgetevents_time64-syscall.patch
poky/meta/recipes-connectivity/openssl/openssl/0004-Fixup-support-for-io_pgetevents_time64-syscall.patch
poky/meta/recipes-connectivity/openssl/openssl/reproducible.patch
poky/meta/recipes-connectivity/openssl/openssl_1.1.1k.bb

Tested:
Can connect via HTTPS, SSH, and ipmitool.
Signed-off-by: Joseph Reynolds <joseph-reynolds@charter.net>

Bump openssl from 1.1.1d to 1.1.1k

---

meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis.inc
meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis_git.bb

Redefine access conditions for mowgli cpld without affecting other
platforms.

witherspoon-pfault-analysis srcrev bump bf357dca56..dd8000ec8d

---

meta-ibm/conf/machine/p10bmc.conf

Change-Id: Ied6ddad5f56d0ddfabd4c2b2f9c510c99e622172

meta-ibm: Update p10bmc.conf

---

meta-phosphor/recipes-phosphor/webui/webui-vue_git.bb

```
initial bump for downstream public
Change-Id: I471286f416b41cb7ecc37b2391000ea756d1d6f3
```

1020: webui-vue: downstream srcrev bump fedc7344df..286325d831

---

meta-phosphor/recipes-phosphor/webui/webui-vue_git.bb

```
Change-Id: I9ad96bdc72811ccfb888cee9fd96669ef717233d
```

1020: webui-vue: downstream srcrev bump fedc7344df..c87be1a2b8

---

meta-phosphor/recipes-phosphor/webui/webui-vue_git.bb

```
Kenneth Fullbright (1):
Removed hashes from files (#334)
Change-Id: I1c8cbf838dd63e5d4c263ca53b95a22e57fc2e75
```

1020.10: webui-vue: downstream srcrev bump 286325d831..924cd305f7

---

meta-phosphor/recipes-phosphor/webui/webui-vue_git.bb

```
Kenneth Fullbright (1):
Removed hashes from files (#334)
Change-Id: I87864870abf41e1a0c6eb8bbca28095f300b9bb6
```

1020: webui-vue: downstream srcrev bump c87be1a2b8..d90d04bcc4

---

meta-ibm/recipes-phosphor/settings/phosphor-settings-manager/disable-Host-Tpm.service
meta-ibm/recipes-phosphor/settings/phosphor-settings-manager/disableHostTpm.sh
meta-ibm/recipes-phosphor/settings/phosphor-settings-manager_%.bbappend

settings: Disable Host Tpm by default for IPS

---

meta-ibm/recipes-phosphor/settings/phosphor-settings-manager/disable-Host-Tpm.service
meta-ibm/recipes-phosphor/settings/phosphor-settings-manager/disableHostTpm.sh
meta-ibm/recipes-phosphor/settings/phosphor-settings-manager_%.bbappend

settings: Disable Host Tpm by default for IPS (#237)

---

meta-phosphor/recipes-phosphor/webui/webui-vue_git.bb

The webui-vue repo uses the ips branch by default

---

meta-ibm/recipes-phosphor/flash/phosphor-hostfw-image.bbappend

Change-Id: Id998b77dbb2a7e70c462e1487a982e55333820cc

meta-ibm: hostfw: Update to latest

---

meta-ibm/meta-witherspoon/recipes-kernel/linux/linux-aspeed/0001-Fix-psu-signal-and-vout-issue.patch

Fix mowgli use Delta(1200W) PSU also using linear-11
conversion formula, it should using linear-16

Fix mowgli's psu vout reading error

---

meta-ibm/meta-witherspoon/recipes-core/systemd/systemd_%.bbappend

Signed-off-by: Steve_LL_Chen <Steve_LL_Chen@wistron>

Enable journal persistence for Mowgli

---

meta-ibm/meta-witherspoon/recipes-core/systemd/systemd_%.bbappend

Signed-off-by: Steve_LL_Chen <Steve_LL_Chen@wistron>

Enable journal persistence for Mihawk(#287)
