meta-openpower/recipes-phosphor/webui/phosphor-webui/df-openpower/config.json, meta-openpower/recipes-phosphor/webui/phosphor-webui_%.bbappend
OpenPower systems use the exisiting D-Bus GUI panel, named "Event log".
This new Redfish Event Log panel was added here:
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/15801
More detail there on why a 2nd event log page was added.
One day would like to share a Event Log panel in the GUI,
but at this time it is not possible due to the field differences.
OpenPower systems still use the following phosphor-logging features:
resolve field (not in the Redfish spec), delete event logs one at a
time (not yet implemented on the backend), and EventID (not in spec).
This is merged in master meta-ibm. 
This is the cherry-pick of the bump. 
See
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-webui/+/22868
(From meta-openpower rev: bc28b6abe52b70b60874fe57ee60ae12e196c359)
Tested: …
=> GUI: Turn off Redfish Event Log

meta-phosphor/recipes-phosphor/ipmi/phosphor-ipmi-host/merge_yamls.py, meta-phosphor/recipes-phosphor/ipmi/phosphor-ipmi-sensor-inventory-mrw-config/config.yaml
This reverts commit 7fb0c049d3a290c8f9d7f7c9690cdef9a97b3c52.
Restore function reverted by
7fb0c049d3a290c8f9d7f7c9690cdef9a97b3c52, swift build issue
has now been resolved.
(From meta-phosphor rev: 7106ecfbc78b7ab9aba84dfa3319455cdc833903)
Merged into master here: https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/23520
Fixes https://github.com/ibm-openbmc/dev/issues/280 
Signed-off-by: Santosh Puranik <santosh.puranik@in.ibm.com>
Change-Id: Iec14a8efc79f9094e6c37e0b1489e4e9ab9406c9
=> Revert "Revert "Accelerator interface for sensorinventory items""

meta-ibm/meta-witherspoon/recipes-phosphor/configuration/acx22-yaml-config/acx22-ipmi-sensors-mrw.yaml
This commit adds the xyz.openbmc_project.Inventory.Item.Accelerator
interface to IPMI GPU functional sensors.
This was something done earlier by commit
f510f7b6b708b22db1f08faf369994f01edd0ddc.
The same is being ported now to the new sensor config YAML.
Tested:
Loaded this change up on a witherspoon. Verified that the
inventory objects created by host-ipmid now implement the
xyz.openbmc_project.Inventory.Item.Accelerator interface.
busctl call xyz.openbmc_project.ObjectMapper /xyz/openbmc_project/object_mapper
xyz.openbmc_project.ObjectMapper GetSubTree sias
"/xyz/openbmc_project/inventory" 0 1
"xyz.openbmc_project.Inventory.Item.Accelerator"
a{sa{sas}} 6
"/xyz/openbmc_project/inventory/system/chassis/motherboard/gv100card0"
....
....
Signed-off-by: Santosh Puranik …
=> Add Accelerator Interface to GPU Sensors

README.md
Added a section on ibm-openbmc, reiterating IBM's commitment to
its continued contribution to the Linux foundation OpenBMC
project.
Merging into master branch.
Tested: https://jbt.github.io/markdown-editor/
Signed-off-by: Gunnar Mills <gmills@us.ibm.com>
=> Add ibm-openbmc info to README

meta-ibm/meta-witherspoon/recipes-phosphor/inventory/phosphor-inventory-manager/associations.json
Code review:
* https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/23979
* Have 3 +1s.
Commit message:
BMCWeb uses ObjectMapper associations to find sensor information for
Redfish.  Due to BMCWeb enhancements for the Power and SensorCollection
schemas, the following Witherspoon association changes are required:
* Remove the "chassis" <-> "all_sensors" association for power supplies.
Power supplies were considered chassis by BMCWeb as a short-term
solution, but they have been moved to the Power schema.
* Add the power supply sensors to the "chassis" <-> "all_sensors"
association for the top level chassis.
* Add other missing power sensors to the "chassis" <->
"all_sensors" association for the top level chassis.  These
associations were temporarily removed due to limitations in the …
=> meta-ibm: witherspoon: Power sensor associations

meta-openpower/recipes-bsp/pdbg/pdbg/proc-thread-control-chipop-based.patch, meta-openpower/recipes-bsp/pdbg/pdbg_2.1.bb
Patch to enable SBE chip-op based start, stop and sreset in pdbg.
Signed-off-by: Jayanth Othayoth <ojayanth@in.ibm.com>
Change-Id: I20d817fe3b7c9e34a917e8aea420350f1659aa70
Conflicts:
meta-openpower/recipes-bsp/pdbg/pdbg_2.1.bb
=> pdbg:SBE chip-op based processor thread control

meta-ibm/meta-witherspoon/recipes-phosphor/configuration/acx22-yaml-config/acx22-ipmi-sensors-mrw.yaml
The CPU cores are currently skipped from inventory update if they
are not present. Suppose the CPU has 20 cores which are present and
the inventory is updated correctly. The inventory would persist this
information. If the CPU is replaced with 16 cores, the inventory would
still show 20 cores since the presence for the 4 cores which are absent
is not updated in the inventory.
This patch ensures that the presence for the cores are updated correctly,
including the ones that are absent. This would differ from the existing
behaviour that inventory objects are created for cores that are not present.
Change-Id: I744210833c10bf8be43ca06d2922844b38fcd6c6
Signed-off-by: Tom Joseph <tomjoseph@in.ibm.com>
=> Remove skipOn for CPU core sensor

meta-ibm/meta-witherspoon/recipes-phosphor/ipmi/phosphor-ipmi-config/ibm-ac-server/channel_config.json
Witherspoon has only one LAN interface which is channel number 1.
The json file provided by the phosphor layer has channel information
for two LAN interfaces. The phosphor layer config file is modified to
mark the channel number 2 as reserved.
Change-Id: I282bd09e84988a67e352fa4d156f1806e4a95824
Signed-off-by: Tom Joseph <tomjoseph@in.ibm.com>
=> Create WS specific channel_config.json

meta-ibm/meta-witherspoon/recipes-phosphor/sensors/phosphor-hwmon_%.bbappend
Enable this config for mihawk so the fan sensors are working, otherwise
hwmon will fail and exit when fans are not working.
Tested: Verify that the fan_tach sensors return -ETIMEOUT when host is
powered off and do not exit with failure.
Change-Id: I5b808183afcdb193ea39d7cd91e978a7902a4d34
=> Mihawk use negative-errno-on-fail config

meta-ibm/meta-witherspoon/conf/machine/mihawk.conf, meta-phosphor/aspeed-layer/recipes-bsp/u-boot/files/0002-board-aspeed-aspeednic-Use-MAC2-for-networking.patch, meta-phosphor/aspeed-layer/recipes-bsp/u-boot/u-boot-aspeed.inc, meta-phosphor/conf/distro/include/phosphor-aspeednic-use-mac2.inc
1. u-boot-aspeed: Add distro feature for mac2 support
2. meta-ibm: Enable mac2 on mihawk platform
=> Enable mac2 on mihawk platform

recipes-connectivity/avahi/avahi-daemon/avahi-daemon-override.conf, recipes-connectivity/avahi/avahi_%.bbappend
service.
Avahi service fails to start when we code update from image which has no
avahi service to image which has avahi service,As part of code update.
we don't touch the persistent file(/etc/group or /etc/password).
Now the image which is going to be updated needs these persistent files
to be updated.
I have tried to add avahi user using extrausers and pkg_postinst scripts
I could see updated /etc/group and /etc/password files with avahi entry
in rootfs build directory, but after code update to this new BMC image
we dont see these udpated files on the system, where as this new image
requires avahi user and the group to be present in the /etc/passwd and
/etc/group on the system.
Implemented service override file to check and create avahi group
and user before starting avahi service. …
=> Avahi:Fix to check and create avahi group and user before starting avahi

meta-ibm/meta-witherspoon/recipes-phosphor/configuration/acx22-yaml-config/acx22-ipmi-sensors-mrw.yaml, meta-ibm/meta-witherspoon/recipes-phosphor/settings/phosphor-settings-manager/ClearHostSecurityKeys-default-zero.override.yml, meta-ibm/meta-witherspoon/recipes-phosphor/settings/phosphor-settings-manager_%.bbappend
Support to set the value for ClearSecurityKeys property which can be used to
indicate when certain security keys need to be cleared or reset those values
back to its default state from the system by the host. This property is mapped
to an IPMI sensor and default value will be zero. Setting this property does
not gurantee a successful operation as additional conditions like the physical
presence pin or jumper settings will be checked by the host to clear/reset the
sensitive data.
Tested: Verified that the property is getting created with the expected
default value as zero and can be updated to different values using ipmitool
or busctl command.
1. Default value output:
busctl get-property xyz.openbmc_project.Settings
/org/open_power/control/host0/ClearHostSecurityKeys …
=> Value setting for IPMI clear security keys

meta-phosphor/recipes-phosphor/ipmi/phosphor-ipmi-host_git.bb, meta-phosphor/recipes-phosphor/ipmi/phosphor-ipmi-net/ipmi-net-firewall.sh, meta-phosphor/recipes-phosphor/ipmi/phosphor-ipmi-net_git.bb
Added dependency for iptables to enable/disable IPMI and added the script
to apply the iptables when the network IPMI starts.
Change-Id: Ie7aa55530f8e0ca789bd05b1c53d1c57f46766ee
Signed-off-by: Tom Joseph <tomjoseph@in.ibm.com>
=> SW470068: Add support for enabling/disabling network IPMI

meta-phosphor/recipes-graphics/obmc-ikvm/obmc-ikvm_git.bb
Include the fix for SW471168, which is merged in master.
=> meta-phosphor: obmc-ikvm: SRCREV bump 23135dd9

meta-phosphor/recipes-connectivity/avahi/avahi-daemon/avahi-daemon-override.conf, meta-phosphor/recipes-connectivity/avahi/avahi_%.bbappend
This is a patch on top of a change already in OP940 that was incorrect
due to a misplaced line feed. This commit updates the code to what is
now in gerrit at:
https://gerrit.openbmc-project.xyz/c/openbmc/meta-phosphor/+/24271
The extra line feed was added to the bbappend due to git requiring some
sort of change to detect the file permission change. git only detects
non-exe to/from exe. This permission change was required to avoid a
warning by systemd.
=> avahi: Ensure user and group added

meta-ibm/meta-witherspoon/conf/machine/mihawk.conf
Change tpm connector instance name to prevent wrong name in bmc yaml
file.
(From meta-ibm rev: dad5e4f56d827cab311d9399a48bd09c26296f15)
Change-Id: I919a8faadd3036b98215b76195602c1f8fb12435
=> mihawk-xml: srcrev bump b9929ba9fd..f6ec5aa0f9

meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan-control-events-config/mihawk/events.yaml
Mihawk can use GPU, so fan control must support GPU thermal sensor.
=> meta-ibm: Mihawk fan control support GPU thermal sensor

meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan-control-events-config/witherspoon/events.yaml, meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan-control-zone-config/witherspoon/zones.yaml
These commits are not in gerrit/upstream and need to be reviewed here first. They will likely be different when pushed upstream due to difference in the OP940 branch and master upstream branch. Some functionality of these commits may be able to be handled differently upstream and/or already done.
These are the yaml updates to support the need for multiple thermal modes altering the fan floor speeds.
***Wait to merge this until the phosphor-fan bump is merged.***
=> Op940 sw473575

meta-ibm/recipes-httpd/nginx/files/nginx-prep-downgrade.service, meta-ibm/recipes-httpd/nginx/nginx-prep-downgrade.bb, meta-ibm/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend
This adds a service which creates a directory needed in case the BMC is
downgraded to a release which used nginx.
The directory must be created in the overlay filesystem (not in the
generated file system) so it will survive the downgrade.  The service
is "harmless" and only creates one additional subdirectory.
This is needed for OpenBMC 2.7 and later systems (which use BMCWeb) and
may be code updated (downgraded) to OpenBMC 2.6 and earlier releases (which
use nginx).
Without this fix, the BMC fails to start its nginx server and does not
provide HTTP, REST, or Web services.  The underlying cause of the server
failing to start is: the directory it needs to write files into does not
is not present.
The problem does not affect the SSH service.  Commands like "systemctl
status nginx" show …
=> nginx: OP940 prepare for downgrade

poky/meta/recipes-core/dropbear/dropbear.inc, poky/meta/recipes-core/dropbear/dropbear/dropbear-disable-weak-ciphers.patch
This is a backport of the poky dropbear disable-weak-ciphers patch which
is in master and will not be accepted into poky/warrior.  This backports
the patch in openbmc/poky/warrior.
The openembedded-core recipe with this patch is here:
https://layers.openembedded.org/layerindex/recipe/4674/
This is needed to avoid regressing the OpenBMC 2.7 SSH security
configuration.  This fix also removes additional weak ciphers as
previously agreed in gerrit code reviews.
The recipe adds a new PACKAGECONFIG disable-weak-ciphers, on by default,
which patches dropbear SSH ciphers.
Tested: Yes
Signed-off-by: Joseph Reynolds <joseph.reynolds1@ibm.com>
Change-Id: I39194acfd405edf7beb4a01e2731cee751bc7bec
Gerrit for patch submission and …
=> dropbear: OP940 disable-weak-ciphers backport

meta-phosphor/recipes-phosphor/users/phosphor-user-manager_git.bb
This dependency was missed in the previous pull request and is required
now to handle the add_groups_workaround.sh script
=> add_groups_workaround requires bash RDEPENDS

meta-openembedded/meta-oe/recipes-graphics/libvncserver/libvncserver_0.9.12.bb, meta-phosphor/recipes-graphics/obmc-ikvm/obmc-ikvm_git.bb
Bump both libvncserver and obmc-ikvm to master levels. The obmc-ikvm commit we
need, 85d0455227ea6bb60f5dc1cf6e67d6e27eed7788, depends on the latest
libvncserver.
=> SW476410:ipkvm: bring SRCREVs to master

meta-ibm/meta-witherspoon/recipes-phosphor/ipmi/phosphor-ipmi-config/ibm-ac-server/channel_config.json
On OP940 and latest master the IPMI channel information for LAN is
802.3 LAN. For backward compatibility of XCAT , it is reverted to
"other-lan".
Signed-off-by: Tom Joseph <tomjoseph@in.ibm.com>
=> SW479257: Revert the medium type to Other LAN

meta-phosphor/recipes-phosphor/preinit-mounts/preinit-mounts/init
During a downgrade, errors from the overlay files have been seen.
Try to recreate the overlay when this happens by re-copying the
files into /etc.
Tested: Put this change in OP930, then on a system running OP940, performed
factory reset, then downgraded to the modified OP930 level and verified the
new code ran and the system booted. Without this change, this downgrade scenario fails.
Defect: https://w3.rchland.ibm.com/projects/bestquest/?defect=SW478084
Change-Id: Idde33213cb0a6bac0b4468e22b3b4fa424508267
=> preinit-mounts: Add check for overlay file errors

meta-ibm/meta-witherspoon/recipes-phosphor/network/phosphor-network_%.bbappend
Prevent the BMC from failing over to the other ethernet port if it
detects a network drop on the one it's using.
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/26411
(From meta-ibm rev: 4c3ea265721c4a1152ae75711af68c6caa29a772)
Change-Id: Id7f3a939e967e661937098a2ea95fdb79e973862
=> meta-ibm: Add the ncsi-netlink service for mihawk

meta-ibm/meta-witherspoon/recipes-phosphor/gpu/phosphor-gpu_git.bb
Close idle channels to avoid device conflicts.
BMC will get the wrong GPU temp when connected to multiple GPUs. The 
reason is that the channel is not closed after reading the data.
=> mihawk: phosphor-gpu SRCREV bump f57188be82..dc27898de5

meta-ibm/meta-witherspoon/recipes-phosphor/gpio/id-button.bb, meta-ibm/meta-witherspoon/recipes-phosphor/gpio/id-button/99-gpio-keys.rules
/dev/input/by-path/platform-gpio-keys-event is not created by udev
while id_button.service is running. In mihawk it takes much more
time for udev to create those files maybe there are more devices
in Mihawk. This patch adds the udev rules to activat the id_button
service. This patch is not quilified to upstream but should be
enough for mihawk OP940
The timing of kernle, udev and id_button service
Nov 01 09:31:11 mihawk kernel: input: gpio-keys as /devices/platform
/gpio-keys/input/input2
Nov 01 09:31:11 mihawk systemd[1]: Started udev Kernel Device Manager.
Nov 01 09:31:17 mihawk systemd[1]: Started udev Coldplug all Devices.
Nov 01 09:31:46 mihawk systemd[1]: phosphor-gpio-monitor@id_button.
service: Main process exited, code=killed, status=6/ABRT
Nov 01 09:31:46 mihawk systemd[1]: …
=> Add udev rules for mihawk id_button.service

meta-phosphor/recipes-core/dropbear/dropbear/0001-implement-expired-password-dialog.patch, meta-phosphor/recipes-core/dropbear/dropbear_%.bbappend, meta-phosphor/recipes-extended/pam/libpam/pam.d/common-auth, poky/meta/recipes-core/dropbear/dropbear/dropbear
This adds a patch from the dropbear email list.  That patch was modified
to work with DROPBEAR_2019.78.  The patch enhances the dropbear SSH
server to respond to SSH client requests to change the password.
The /etc/pam.d/dropbear config file is enhanced so PAM will allow
dropbear to change the password.  The /etc/pam.d/common-auth file is
enhanced to tolerate the initial SSH auth failure and allow the password
change to succeed.
tested: yes, via the OpenSSH client.
Signed-off-by: Joseph Reynolds <joseph-reynolds@charter.net>
=> dropbear ssh server expired password dialog

meta-ibm/meta-witherspoon/recipes-phosphor/configuration/acx22-yaml-config/mihawk/acx22-ipmi-hwmon-sensors.yaml
We think fan is a necessary sensor in ipmi sensor list.
Tested: Use ipmitool sdr to check it.
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/27436
(From meta-ibm rev: 5bdc8591ac5e6ce708fdc0788806cb89452c3b14)
Change-Id: I87acef1dcfe11bc532eac5412375133b56f40320
=> meta-ibm: Modify ipmi config

meta-ibm/meta-witherspoon/recipes-phosphor/dbus/thermal-policy/mihawk/thermal-policy.yaml
1. According to the thermal team test results, the cpu core should be
shutdown when it exceeds 95 degrees Celcius.
2.mihawk's ambient temperature exceeds 45 degrees Celcius should be
shutsown to avoid system damage.
Tested:
Cpu core exceeds 95 degrees Celcius or ambient exceeds 45 degrees
Celcius system will shutdown.
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/27435
(From meta-ibm rev: 7f94a4b3a7c3d7346ae4b1bade6287ea1a70c41a)
Change-Id: I303a5047dc0b29e46829f4b838eaa6f151b13735
=> meta-ibm: Modify mihawk themal policy

meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan-control-events-config/mihawk/events.yaml, meta-ibm/meta-witherspoon/recipes-phosphor/sensors/phosphor-hwmon/mihawk/obmc/hwmon/ahb/apb/bus@1e78a000/i2c-bus@400/emc1403@4c.conf
According to our thermal team test report, we need to adjust the fan
control event.
Tested
Fan speed will be based on new fan control events.
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/27509
(From meta-ibm rev: f242630e5a8195eeef089f01537b9be4fde000a2)
Change-Id: Ib4c296f128d625e78387cead26c46c76faa39535
=> meta-ibm: Adjust the mihawk fan control event

meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/mihawk/pseq-monitor-pgood.service
Because mihawk's pseq-pgood-monitor interval is too short, 
pseq-pgood-monitor runs early and reads power errors which 
don't exist, so the adjustment interval is 5s to 10s.
Tested:
Test system on the first IPL after flashing firmware.
=> Fix pseq-pgood-monitor's interval for mihawk

meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan-control-events-config/mihawk/events.yaml
Fan speed can be increased when occ or ambient is abnormal, so add the
monitor of the ambient and OCC control services.
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/27624
=> meta-ibm: Add a mechanism to monitor ambient and occ

meta-ibm/meta-witherspoon/recipes-phosphor/leds/mihawk-led-manager-config/led.yaml
Add led fault event, fault led will turn on when cpu or dimm or other
components fail
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/27845
(From meta-ibm rev: f0aaa6f39f61366a6599d1e571f1eada4bf93b1c)
Change-Id: Ifdd49dab35d915cb7d9ff095e6571fba42801bba
=> meta-ibm: Add led manager event

meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan-control-events-config/mihawk/events.yaml, meta-ibm/meta-witherspoon/recipes-phosphor/gpu/phosphor-gpu_git.bb
1. Update phosphor-gpu version
2. Add a monitor gpu service. When the gpu service fails, the fan can
ensure that there is enough fan speed.
Because the phosphor-gpu currently only uses the branch in op940, it 
directly pulls the request.
=> Update phosphor-gpu version and add monitor gpu service

meta-ibm/meta-witherspoon/recipes-kernel/linux/linux-aspeed/0001-wistron-wps.patch, meta-ibm/meta-witherspoon/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend, meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/mihawk/obmc/power-supply-monitor/power-supply-monitor-0.conf, meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/mihawk/obmc/power-supply-monitor/power-supply-monitor-1.conf, meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/mihawk/pseq-monitor.service, meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/swift/pseq-monitor.service, meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/witherspoon/pseq-monitor.service, meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis_git.bb
1. Fix patch error:
commit 39eed9fc1c7baccca3e4ae17a16f045baf9d6096
Fix psu-driver error, and re-pull request to OP940.
Because this part is still reviewed in the upstream,
we're going to release the new version,
we create a patch of it in OP940 first.
We'll remove this patch after the upstream review passes.
https://www.spinics.net/lists/kernel/msg3339443.html 
2. Remove psu-sync function & add pseq-monitor for mihawk:
commit 77cee448fa196405bda17debe1003a5c111f9464
2.1 Remove psu-sync function for mihawk.
2.2 Add pseq-monitor for mihawk via modifying 
witherspoon-pfault-analysis_git.bb.
=> Fix patch error & remove psu-sync function & add pseq-monitor for mihawk to OP940

meta-ibm/meta-witherspoon/recipes-phosphor/chassis/avsbus-control/mihawk/avsbus-disable@.service, meta-ibm/meta-witherspoon/recipes-phosphor/chassis/avsbus-control/mihawk/avsbus-enable@.service
Currently avsbus-disable will be executed after power_up to 1.
We found that this will cause power on fail, so avsbus-disable should
be performed before power on.
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/28167
=> meta-ibm: Change the order of avsbus-disable

meta-aspeed/recipes-kernel/linux/linux-aspeed_git.bb
5.3 includes a number of fixes that OP940 needs.
Signed-off-by: Eddie James <eajames@linux.ibm.com>
=> linux-aspeed: Update Linux to final v5.3

meta-phosphor/recipes-extended/pam/libpam/pam.d/common-auth
This patch apples the 300 second account lockout policy to the root user account; the root account will have the same default behavior as other user accounts.  Specifically: Lockout authentication for 5 minutes after 5 failed authentication attempts.
The behavior of the pam_tally2 module (as configured here) is:
- The account is locked out after 5 or more unsuccessful authentication attempts.  (This is tracked per user.)
- When an account is locked out, no authentication attempts will succeed until the 5 minutes has elapsed.  Any subsequent attempts will reset the lockout period.  Only a successful authentication will clear the lockout.
Note that the AccountLockoutThreshold and AccountLockoutDuration properties in the Redfish AccountService do not apply to the root user, and there are no …
=> lockout after failed root authentication

meta-ibm/meta-witherspoon/recipes-phosphor/ipmi/phosphor-ipmi-config/mihawk/dev_id.json
Currently mihawk is missing information about dev id.
(From meta-ibm rev: 28bafefc05285df52eab617ea2158b3886dc93a8)
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/29223
Change-Id: I02b138a1830e0c4627c70b338d31cb7dbaa2d75c
=> meta-ibm: Add dev_id.json for mihawk

meta-ibm/meta-witherspoon/recipes-phosphor/vpd/mihawk-openpower-fru-inventory/inventory
Added the BMC inventory for mihawk.
(From meta-ibm rev: 95efbf1fdb48951294a3832137d4c1a56fcab3a2)
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/29726
Change-Id: I3478e33ce305324d2041e69d79d8873585cae23d
=> meta-ibm: Add BMC EEPROM

meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan-control-events-config/mihawk/events.yaml
Fan control must support NVMe SSD thermal sensor.
Tested: Fan speed is automatically controlled when using NVMe SSD
(From meta-ibm rev: 4dc75c91139e71ee5f42ba27ddacf46815c8aa8b)
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/29882
Change-Id: Idb156ebe12d98b26faa7781b462e11b38af5ae7c
=> meta-ibm: Mihawk fan control support NVMe thermal sensor

meta-ibm/meta-witherspoon/recipes-phosphor/dbus/thermal-policy/mihawk/thermal-policy.yaml
Mihawk's GPU temperature exceeds 92 degrees Celcius should be shutsown
to avoid GPU damage.
Tested:
GPU temperature exceeds 92 degrees Celcius system will shutdown.
(From meta-ibm rev: 623eb4dda626dd3dfb3f14d9afa4e10c86d3bbca)
https://gerrit.openbmc-project.xyz/c/openbmc/meta-ibm/+/27533
Change-Id: Id085afa2a7d7a29a42cd5d508a03fb64dd53c108
=> meta-ibm: Add GPU themal policy

meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan_%.bbappend
Add the phosphor-fan-control-init service back in to trigger the
obmc-fan-control-ready target which is used to start
phosphor-fan-monitor. It was not realized that this target was set
within the fan control application's init mode.
Tested:
Built witherspoon image containing phosphor-fan-control-init service
Service is started at poweron and sets obmc-fan-control-ready target
Fan monitor service now starts
Change-Id: I6a6b9eb1bb46ad9030e0fb02348fe5d246c85f99
Signed-off-by: Matthew Barth <msbarth@us.ibm.com>
=> meta-ibm: witherspoon: phosphor-fan-control-init service

meta-ibm/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend, meta-phosphor/recipes-phosphor/ipmi/files/fixup-file-modes.service, meta-phosphor/recipes-phosphor/ipmi/fixup-file-modes.bb
Adds a service to fixup IPMI file modes so only the root user can access.
This is not yet fixed in upstream.
Tested:
- Service runs correctly per journalctl --unit=fixup-file-modes.
- Access via ipmitool works correctly.
- Changing password via ipmitool works correctly.
- Changing password via Redfish works correctly.
- Adding and removing user works correctly.
- File mode is not changed when user is modified.
Signed-off-by: Joseph Reynolds <joseph-reynolds@charter.net>
=> user-management: fixup file modes

meta-ibm/meta-witherspoon/recipes-phosphor/ipmi/wistron-ipmi-oem_git.bb, meta-ibm/meta-witherspoon/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend
In order to detect the riser card on the mihawk platform.
(From meta-ibm rev: a50f69fb50ab68137ce1b95d79ccb703c97e47c4)
Change-Id: Ief0019f08cc14f3733ba5db67fcf218f46812bb2
=> meta-ibm: Add mihawk ipmi oem command

meta-ibm/meta-witherspoon/recipes-phosphor/fans/phosphor-fan-control-events-config/mihawk/events.yaml, meta-ibm/meta-witherspoon/recipes-phosphor/gpu/phosphor-gpu_git.bb
Fan control must support 250 soc thermal sensor.
Tested: Fan speed is automatically controlled when using 250 soc
https://gerrit.openbmc-project.xyz/c/openbmc/openbmc/+/34724
(From meta-ibm rev: 05540e77d337f466bc339715153704edff3f6b88)
Change-Id: Ic17854a8556b5878bf506bfafd64762315390c39
=> meta-ibm: Mihawk fan control support 250 soc thermal sensor

meta-openpower/recipes-bsp/ecmd/croserver_git.bb, meta-openpower/recipes-bsp/ecmd/files/croserver.service, meta-openpower/recipes-phosphor/packagegroups/packagegroup-op-apps.bb
These are pulled from upstream and add the cronus server to the BMC flash. Moving to the 5.4 kernel changed the FSI kernel interface so this commit packages in the cronus server that handles this change.
=> Op940 add cronus service

meta-openpower/recipes-bsp/ecmd/croserver_git.bb
Per Steven Janssen, this is the minimum bump required to satisfy
manufacturing test requirements.
Jason Albert (13):
Add ecmdChipTarget hash support to pyapi
Defined __deepcopy__ functions on classes
Added python support for vector<vector<databuffer>>
Fix python3 problems in config/build
Fixed coredump due to accessing empty list
Fix the __deepcopy__ implementation
Force python 3 and updated logic around use of linux_distribution
Big update to ecmdDllSpy.C
Merge pull request #386 from thejta/spy-update
Fixed in memory spy db performance
Merge pull request #387 from thejta/spy-performance-update
Added getSpyImages support
Merge pull request #390 from thejta/spy-image-support
Joachim Fenkes (7):
pyapi: Add support for vector<string> arguments
pyecmd: Support list-of-string output arguments, …
=> croserver bump 6c0348..46282c

meta-aspeed/recipes-kernel/linux/linux-aspeed_git.bb
Picks up max31785 fan driver workaround
Signed-off-by: Andrew Geissler <geisonator@yahoo.com>
=> kernel: bump up to 5.4.62

meta-openpower/recipes-bsp/pdbg/pdbg_3.0.bb
The 3.0 release follows from the 2.5-rc1. The changelog for 3.0 is as
follows:
Major upstream change was the split out the access method from the
device-tree representation to enable backend agnostic system device
trees.
Other notable features:
- Swift support
- get/putmempba
- Added SBEFIFO backend
- Expanded use of SBEFIFO chipops
=> pdbg: Move to v3.0

meta-openpower/recipes-phosphor/flash/openpower-software-manager_git.bb
Add the 940 PNOR level as the Minimum Ship Level.
Change-Id: I7c438b3689e0928bf3f3572cc6ac2cb9920b884b
=> openpower-software-manager: Add 940 PNOR MSL level

meta-phosphor/recipes-phosphor/dump/phosphor-debug-collector/obmc-dump-monitor.service
phosphot-dump-monitor adds watch on systemd core dump path to
detect any new core files created to initiate a dump. On some
systems systemd core dump package is not pulled, due to this
phosphor-dump monitor service logs error and tries retry for 3 times.
Modified to start phosphor-dump-monitor service only when the
systed core dump path exists.
Tried to add Requires on systedm core dump service but as it is
a template version going with path approach.
Tested:
1) Removed systemd dump folder and restarted dump-monitor service
and ensured that there are no errors logged
(From meta-phosphor rev: 7a99220eaae763113372477c3d25039284802ef7)
Signed-off-by: Marri Devender Rao <devenrao@in.ibm.com>
Change-Id: Ibeb83cde454bf4c6fc6c6827a25705649ceaabe5
Signed-off-by: Brad Bishop …
=> phosphor-dump-monitor- Fix failure for not finding core dump path

meta-openpower/recipes-bsp/pdbg/pdbg_3.1.bb
1) Fix to make threadstatus to work with sbefifo
2) Do not free sbefifo during release of all targets
3) Fix to make SPR/GPR work with SBEFIFO on p9
Signed-off-by: Lakshminarayana R. Kammath <lkammath@in.ibm.com>
=> pdbg revision bump to v3.1

meta-phosphor/classes/mrw-rev.bbclass
gen_ipmi_sensor: Add occ path conversion conditions for one CPU
When the platform has only one CPU, the occ inventory path will be
/system/chassis/motherboard/cpu/occ.
So checkOccPathFixup cannot be successfully converted to the correct
application d-bus path.
https://gerrit.openbmc-project.xyz/c/openbmc/phosphor-mrw-tools/+/37463
=> phosphor-mrw-tools srcrev bump 715c97ea..3d7698c2

meta-ibm/meta-witherspoon/recipes-phosphor/ipmi/wistron-ipmi-oem_git.bb
Ben Pai (1):
Add wistron oem command to switch 250 soc image
(From meta-ibm rev: 3aa9904064a954031fac32b462c26c0b6d541ef1)
Change-Id: I6cc97288c35a1ac1f97f55ad0fe179dce9636bb0
Signed-off-by: Andrew Geissler <openbmcbump-github@yahoo.com>
=> wistron-ipmi-oem: srcrev bump 44cee319dd..ba89a1ea57

meta-ibm/meta-witherspoon/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend, meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/mowgli/obmc/power-supply-monitor/power-supply-monitor-0.conf, meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/mowgli/obmc/power-supply-monitor/power-supply-monitor-1.conf, meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/mowgli/pseq-monitor-pgood.service, meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis/mowgli/pseq-monitor.service, meta-ibm/meta-witherspoon/recipes-phosphor/power/witherspoon-pfault-analysis_git.bb
Implement power-fault-monitor in Mowgli.
Add Macro to distinguish Mihawk and Mowgli to ensure
that the part of code used by Mowgli can be built.
=> Implement power-fault-monitor in Mowgli

meta-ibm/meta-witherspoon/recipes-kernel/linux/linux-aspeed/0001-Add-mowgli-platform.patch
Added RTC driver for mowgli.
Signed-off-by: Ben Pai Ben_Pai@wistron.com
We have added a new patch to linux, and it is still under review.
So we also need to update mowgli dts patch.
https://lkml.org/lkml/2021/1/21/208
=> meta-ibm: Update mowgli linux patch

meta-ibm/meta-witherspoon/recipes-phosphor/settings/phosphor-settings-manager/PowerRestorePolicy-default-restore.override.yml, meta-ibm/meta-witherspoon/recipes-phosphor/settings/phosphor-settings-manager_%.bbappend
Power Restore Policy default is set to Restore.
=> meta-ibm: Power Restore Policy default to Restore

meta-ibm/meta-witherspoon/recipes-phosphor/network/network/0001-Let-usb-network-be-static-ip.patch, meta-ibm/meta-witherspoon/recipes-phosphor/network/phosphor-network_%.bbappend
We found that the usb0 ip will be cleared when swtiching the ip mode
between DHCP and Static.
As long as the ip starting with "169.254", the ip mode will be regarded
as linklocal.
Because the usb0 ip of mowgli is 169.254.95.120, we need to add this
this special condition to avoid this issue.
=> meta-ibm: To avoid usb ip is reset issue

meta-ibm/meta-witherspoon/recipes-phosphor/network/phosphor-network_%.bbappend
Prevent the BMC from failing over to the other ethernet port if
it detects a network drop on the one it's using.
=> Add the ncsi-netlink service for mowgli

meta-ibm/meta-witherspoon/recipes-phosphor/ipmi/phosphor-ipmi-config/mowgli/channel_config.json
Because the usb ip of HMC os will not be changed by the user, the usb0
of bmc must also be hidden.
=> meta-ibm: Remove usb0 from channel config

meta-aspeed/recipes-kernel/linux/linux-aspeed_git.bb, poky/meta/lib/oe/utils.py
I backported an upstream yocto fix (c301e66) so that OP940 can build on machines with gcc10.
The Linux bump moves us to the 5.4.119 Linux kernel which includes the latest security updates plus this fix from @eddiejames 
```
commit 8aab1a9ba269a3b012ee850ba7e33d09cb73000f
Author: Eddie James <eajames@linux.ibm.com>
Date:   Thu Apr 29 10:13:36 2021 -0500
hwmon: (occ) Fix poll rate limiting
The poll rate limiter time was initialized at zero. This breaks the
comparison in time_after if jiffies is large. Switch to storing the
next update time rather than the previous time, and initialize the
time when the device is probed.
Fixes: c10e753d43eb ("hwmon (occ): Add sensor types and versions")
Signed-off-by: Eddie James <eajames@linux.ibm.com>
Link: …
```
=> Op940 5.4.119 kernel bump

meta-ibm/meta-witherspoon/recipes-phosphor/vpd/mihawk-openpower-fru-vpd-layout/layout.yaml
The vendor data (VNDR) record is for vendor-specific data. The vendor
defines the data format within the IN keyword.
Tested: Finding Model in Inventory interface
- busctl introspect  xyz.openbmc_project.Inventory.Manager /xyz/openbmc_project/inventory/system/chassis/motherboard/bmc
output:
[[0;1;39mxyz.openbmc_project.Inventory.Decorator.Asset      [[0m interface -         -            -
.BuildDate                                          property  s         ""           emits-change writable
.Manufacturer                                       property  s         ""           emits-change writable
.Model                                              property  s         "OEM"        emits-change writable
.PartNumber                                         property  s         "" …
=> meta-ibm: Add Model to asset interface

meta-ibm/recipes-phosphor/bmcweb/bmcweb/0001-Revert-Add-concurrent-KVM-sessions-support.patch, meta-ibm/recipes-phosphor/bmcweb/bmcweb_%.bbappend
IBM decided to not support multi-session of KVM on Mowgli.
=> meta-ibm: Mowgli's bmcweb only allows one KVM session

meta-ibm/recipes-phosphor/bmcweb/bmcweb/0001-Revert-Add-concurrent-KVM-sessions-support.patch
Add a condition in onmessage to check whether the session exists, so as
to avoid BMCweb from crashing when multiple users try to use KVM at the
same time.
=> meta-ibm: Fix the KVM session patch of Mowgli

meta-aspeed/conf/machine/include/ast2600.inc, meta-aspeed/recipes-aspeed/python/socsec_git.bb, meta-aspeed/recipes-bsp/u-boot/u-boot-aspeed-sdk_2019.04.bb, meta-ibm/conf/machine/p10bmc.conf, meta-openembedded/meta-python/recipes-devtools/python/python3-ecdsa_0.17.0.bb, meta-openembedded/meta-python/recipes-devtools/python/python3-gmpy2_2.0.8.bb
Hardware root of trust support for P10 BMC platforms.
Upstream series: https://gerrit.openbmc-project.xyz/q/topic:%22socsec-sign-p10bmc%22+(status:open%20OR%20status:merged)
=> socsec sign p10bmc

meta-ibm/recipes-phosphor/vpd/ibm-vpd-parser/50001000.json, meta-ibm/recipes-phosphor/vpd/ibm-vpd-parser/50001000_v2.json, meta-ibm/recipes-phosphor/vpd/ibm-vpd-parser/50001001.json, meta-ibm/recipes-phosphor/vpd/ibm-vpd-parser/50001001_v2.json, meta-ibm/recipes-phosphor/vpd/ibm-vpd-parser/50001002.json
This commit adds fan VPD data to Rainier JSONs.
The Rainier fans do not have an eeprom and hence the need
to "hardcode" certain VPD needed by the hypervisor.
Signed-off-by: Santosh Puranik <santosh.puranik@in.ibm.com>
=> Add Fan VPD Data

meta-phosphor/recipes-core/systemd/obmc-targets.bb, meta-phosphor/recipes-core/systemd/obmc-targets/obmc-mapper.target, meta-phosphor/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bb, meta-phosphor/recipes-phosphor/state/phosphor-state-manager-systemd-links.inc, meta-phosphor/recipes-phosphor/state/phosphor-state-manager_git.bb
See this commit for more info on function and testing:
https://github.com/openbmc/phosphor-state-manager/commit/0d1c3f1f9329c853677f0581287afef83eeea0f0
phosphor-state-manager: srcrev bump 65bfcf5792..0d1c3f1f93
Andrew Geissler (1):
host-check: discover host state within state manager
Change-Id: I04129b1838118efceb1d073539d01d6e1af99eec
=> host-check: check host state on startup of host manager

meta-ibm/recipes-phosphor/vpd/ibm-vpd-parser/50001001.json, meta-ibm/recipes-phosphor/vpd/ibm-vpd-parser/50001001_v2.json
Fix a typo in the part numbers for Rainier 2U fans.
02YK327 ==> 02YK237
Signed-off-by: Santosh Puranik <santosh.puranik@in.ibm.com>
=> Fix PartNumber For Rainier 2U Fans

meta-ibm/meta-witherspoon/recipes-phosphor/network/network/disableETH1.sh, meta-ibm/meta-witherspoon/recipes-phosphor/network/network/ncsi-netlink-mowgli.service, meta-ibm/meta-witherspoon/recipes-phosphor/network/phosphor-network_%.bbappend, meta-ibm/meta-witherspoon/recipes-phosphor/vpd/mihawk-openpower-fru-vpd-layout/layout.yaml
The VPD B3 keyword in the VINI record is set to "ETH" to know that the
dedicated NIC has been removed.
If the "ETH" is detected, the unused services will be disabled:
first-boot-set-mac@eth1.service.
=> meta-ibm: Dynamically disable eth1.service

meta-ibm/meta-witherspoon/recipes-phosphor/console/obmc-console/mihawk/obmc-console.conf, meta-ibm/meta-witherspoon/recipes-phosphor/console/obmc-console/mowgli/obmc-console.conf
The host team has requested a bump in their allocated log size. ([link](https://github.com/open-power/ibm-wistron-collaboration/issues/12))
Increase the console log size of Mihawk and Mowgli from the default
16K to 256K.
Testing: Loaded on system and caused a lot of traffic in host console
and verified /var/log/obmc-console.log did not grow beyond 256K and
properly wrapped.
=> meta-ibm: Increase host console log to 256K

meta-ibm/meta-witherspoon/recipes-phosphor/packagegroups/packagegroup-obmc-apps.bbappend
The PACKAGECONFIG option is passed to build this feature for both
systems but to install it, need to add the package
This feature copies certain files over to the alternate flash filesystem
so that in situations where a fail over occurs, things like the network
configuration will still work.
=> mowgli:mihawk: add phosphor-software-manager-sync

meta-ibm/recipes-kernel/linux/linux-aspeed/0001-i2c-Allow-throttling-of-transfers-to-client-devices.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0002-pmbus-ucd9000-Throttle-SMBus-transfers-to-avoid-poor.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0003-ucd9000-Add-a-throttle-delay-attribute-in-debugfs.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0004-fsi-run-clock-at-100MHz.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0005-pmbus-core-Add-a-one-shot-retry-in-pmbus_set_page.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0006-pmbus-max31785-Add-a-local-pmbus_set_page-implementa.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0007-pmbus-max31785-Retry-enabling-fans-after-writing-MFR.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0008-ARM-dts-aspeed-Rainier-Add-fan-controller-properties.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0009-ARM-dts-aspeed-Everest-Add-fan-controller-properties.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0010-ARM-dts-aspeed-Rainier-4U-Delete-fan-dual-tach-prope.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0011-ARM-dts-aspeed-Add-Rainier-2U-and-4U-device-trees-fo.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0012-ARM-dts-aspeed-Everest-and-Rainier-Add-bmc-managemen.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0013-ARM-dts-aspeed-everest-Specify-I2C8-mux-reset-gpio.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0014-hwmon-occ-Delay-hwmon-registration-until-user-reques.patch, meta-ibm/recipes-kernel/linux/linux-aspeed/0015-leds-pca955x-throttle-i2c-transfers.patch, meta-ibm/recipes-kernel/linux/linux-aspeed_%.bbappend
Change-Id: I195cc8490e1af1a481db6e446331bf40ba30bd23
=> 1020: Linux patches

meta-openpower/recipes-phosphor/occ/openpower-occ-control_git.bb
This test doesn't compile when I build the Romulus BMC. It's a convention that we disable test in Yocto builds.
refer: https://github.com/openbmc/openbmc/commit/d6c0eef5d8d630cad4f7daa61e8f8b79c01f5293
=> meta-openpower: openpower-occ-control:disable test

meta-ibm/recipes-phosphor/ibm-acf/ibm-acf.bb
=> The ibm-acf repo uses the ips branch by default

meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager-system.bb, meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager-system/system.yaml, meta-ibm/recipes-phosphor/inventory/phosphor-inventory-manager_%.bbappend
Since VPD does not obtain the Manufacturer of bmc, and on the IPS machine, the default Manufacturer is "Inspur Power Systems", so add a default value for Manufacturer.
=> ips: Add Manufacturer to IPS branch

meta-phosphor/recipes-phosphor/configuration/entity-manager_git.bb, meta-phosphor/recipes-phosphor/interfaces/bmcweb_git.bb, meta-phosphor/recipes-support/boost/boost-1.81.0.inc, meta-phosphor/recipes-support/boost/boost.inc, meta-phosphor/recipes-support/boost/boost_1.81.0.bb
```
Bonnie Lo (1):
schemas: Add properties for pid and pid_zone
Matthew Barth (2):
configs:Storm King: Update ambient thresholds
configs: Blyth & Storm King ambient sensor thresholds
Kumar Thangavel (2):
Add a helper function copyRestFRUArea to updateFRUProperty
Refactor : Add a helper function findIndexForFRU to
Jim Wright (2):
Add support for 110v input voltage on 2000W power supply
Allow 2 PS in Rainier 1s4u 1000W configuration
Joel Stanley (1):
configs: Update RTC battery pin to upstream name
Rashmica Gupta (1):
storm king: Add Ambient Virtual Temperature Sensor
Jayashree Dhanapal (1):
Add a new configuration file for Twinlake board
Andrew Geissler (3):
format: misc changes needed in downstream patches
Merge branch '1050' into 1050-upstream-rebase
Merge pull request #40 from …
```
=> 1050.00: entity-manager: downstream srcrev bump 1f302d72eb..d88b8bc129 & Pull in boost 1.81.0 & bmcweb: downstream srcrev bump ba77f029cc..3086ac5ca4

meta-ibm/recipes-phosphor/flash/phosphor-software-manager_%.bbappend
Enable the minimum ship level format for p10bmc systems to match a string that starts with some characters such as "ibm", followed by 2 numbers for the processor version such as "10", followed by the tag number.
Change-Id: I4f3572db75b4fc1bb3c90c8c952d428d329b5d3a
=> meta-ibm: flash: Add Minimum Ship Level format
